ALTER TYPE "ActivityEventType" ADD VALUE 'CAMERA_STARTED';
ALTER TYPE "ActivityEventType" ADD VALUE 'CAMERA_PERMISSION_DENIED';
ALTER TYPE "ActivityEventType" ADD VALUE 'CAMERA_ERROR';
ALTER TYPE "ActivityEventType" ADD VALUE 'CAMERA_DISCONNECTED';
ALTER TYPE "ActivityEventType" ADD VALUE 'FACE_NOT_DETECTED';
ALTER TYPE "ActivityEventType" ADD VALUE 'FACE_DETECTED';
ALTER TYPE "ActivityEventType" ADD VALUE 'MULTIPLE_FACES_DETECTED';
